# Generated by Django 4.2.1 on 2023-05-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('blood_group', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('vol_of_blood', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
